# Generated by Django 4.0.4 on 2022-05-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Construction type')),
            ],
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Heating')),
            ],
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Offer type')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Property type')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('neighborhood', models.CharField(blank=True, max_length=60, verbose_name='Neighborhood')),
                ('square_meters', models.IntegerField(verbose_name='Square meters')),
                ('number_of_rooms', models.IntegerField(blank=True, null=True, verbose_name='Number of rooms')),
                ('bathroom', models.IntegerField(blank=True, null=True, verbose_name='Bathroom')),
                ('bedroom', models.IntegerField(blank=True, null=True, verbose_name='Bedroom')),
                ('balcony', models.IntegerField(blank=True, null=True, verbose_name='Balcony')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
                ('parking', models.BooleanField(blank=True, default=False, null=True, verbose_name='Parking')),
                ('garage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Garage')),
                ('basement', models.BooleanField(blank=True, default=False, null=True, verbose_name='Basement')),
                ('garret', models.BooleanField(blank=True, default=False, null=True, verbose_name='Garret')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('construction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='post.constructiontype')),
                ('heating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='post.heating')),
                ('offer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.offertype')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.propertytype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
