# Generated by Django 4.0.4 on 2022-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='for_contact',
            field=models.CharField(max_length=100, null=True, verbose_name='For contact'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_picture',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Main picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_1',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_10',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 10'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_2',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_3',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 3'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_4',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 4'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_5',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 5'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_6',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 6'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_7',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 7'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_8',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 8'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_9',
            field=models.ImageField(default='default_property.jpg', upload_to='property_pictures', verbose_name='Picture 9'),
        ),
    ]
