# Generated by Django 4.0.4 on 2022-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_balcony_post_basement_post_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_1',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_10',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 10'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_2',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_3',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_4',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_5',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_6',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 6'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_7',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 7'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_8',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 8'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture_9',
            field=models.ImageField(upload_to='property_pictures', verbose_name='Picture 9'),
        ),
    ]
